spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    error:
      whitelabel:
        enabled: false