spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zuado
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  server:
    error:
      whitelabel:
        enabled: false


