insert into TB_ALUNO (MATRICULA, NOME_ALUNO, EMAIL_ALUNO, IDADE_ALUNO) values (1, 'Edy', 'eboyington0@twitpic.com', 48);
insert into TB_ALUNO (MATRICULA, NOME_ALUNO, EMAIL_ALUNO, IDADE_ALUNO) values (2, 'Abner', 'ameert1@yandex.ru', 99);
insert into TB_ALUNO (MATRICULA, NOME_ALUNO, EMAIL_ALUNO, IDADE_ALUNO) values (3, 'Glynn', 'gstennings2@mediafire.com', 88);
insert into TB_ALUNO (MATRICULA, NOME_ALUNO, EMAIL_ALUNO, IDADE_ALUNO) values (4, 'Eustace', 'erubertis3@admin.ch', 72);
insert into TB_ALUNO (MATRICULA, NOME_ALUNO, EMAIL_ALUNO, IDADE_ALUNO) values (5, 'Carmine', 'cbellin4@nationalgeographic.com', 11);
insert into TB_ALUNO (MATRICULA, NOME_ALUNO, EMAIL_ALUNO, IDADE_ALUNO) values (6, 'Wilmar', 'wmoretto5@blogtalkradio.com', 45);
insert into TB_ALUNO (MATRICULA, NOME_ALUNO, EMAIL_ALUNO, IDADE_ALUNO) values (7, 'Henri', 'hwermerling6@dagondesign.com', 33);
insert into TB_ALUNO (MATRICULA, NOME_ALUNO, EMAIL_ALUNO, IDADE_ALUNO) values (8, 'Alan', 'amccartan7@nyu.edu', 91);
insert into TB_ALUNO (MATRICULA, NOME_ALUNO, EMAIL_ALUNO, IDADE_ALUNO) values (9, 'Lucky', 'lshubotham8@vkontakte.ru', 73);
insert into TB_ALUNO (MATRICULA, NOME_ALUNO, EMAIL_ALUNO, IDADE_ALUNO) values (10, 'Ernestus', 'ebracknall9@booking.com', 72);INSERT INTO TB_CURSO  (ID_CURSO, NOME_CURSO) VALUES (2, 'GREGO');